name: bingr
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  tmdb_api: ^2.2.0
  carousel_slider: ^5.0.0
  http: ^1.2.2
  animated_text_kit: ^4.2.2
  flutter_native_splash: ^2.4.3
  shared_preferences: ^2.3.3
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  speech_to_text: ^7.0.0
  avatar_glow: ^3.0.1

flutter_native_splash:
  color: "#676e68"
  image: "assets/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.2"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/

